spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
            github:
              client-id: your-github-client-id
              client-secret: your-github-client-secret
              scope:
                - user:email
                - read:user

        provider:
          google:
            issuer-uri: https://accounts.google.com
            github:
              issuer-uri: https://github.com



